# Travis CI configuration
# https://travis-ci.org/borntyping/python-dice

language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35  
  - TOXENV=pypy
install:
  - pip install tox
script:
  - tox
